# Generated by Django 5.0.2 on 2024-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
